[package]
name = "json_interface"
version = "0.1.0"
authors = ["mik90 <kaliman.mike@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = "1.0"
serialport = "3.3.0"